package e2e

import "github.com/gobuffalo/packr"

// !!! GENERATED FILE !!!
// Do NOT hand edit this file!!
// It is recommended that you DO NOT check into this file into SCM.
// We STRONGLY recommend you delete this file after you have built your
// Go binary. You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
	packr.PackJSONBytes("static", "index.html", "\"PGRpdiBpZD0iYXBwIj4KCTxuYXYgY2xhc3M9Im5hdmJhciIgcm9sZT0ibmF2aWdhdGlvbiIgYXJpYS1sYWJlbD0ibWFpbiBuYXZpZ2F0aW9uIj4KCQk8ZGl2IGNsYXNzPSJuYXZiYXItYnJhbmQiPgoJCQk8YSBjbGFzcz0ibmF2YmFyLWl0ZW0iIGhyZWY9Imh0dHBzOi8vYXZvY2V0LmlvIj4KCQkJCTxwIGNsYXNzPSJ0aXRsZSIgc3R5bGU9InBhZGRpbmc6MC41cmVtOyBtYXJnaW46MC41cmVtOyI+Y2FuYXJ5PC9wPgoJCQk8L2E+CgkJPC9kaXY+Cgk8L25hdj4KCTxkaXYgY2xhc3M9ImNvbnRhaW5lciI+CgkJPGRpdiBjbGFzcz0iY29sdW1ucyBpcy1tdWx0aWxpbmUiPgoJCQk8ZGl2IGNsYXNzPSJjb2x1bW4gaXMtaGFsZiIgdi1mb3I9InRlc3QgaW4gb2JqZWN0RGF0YSI+CgkJCQk8ZGl2IGNsYXNzPSJoYXMtdGV4dC13aGl0ZSIgc3R5bGU9ImJvcmRlci1yYWRpdXM6IDNweDsgcGFkZGluZzogMnJlbTsiIHYtYmluZDpjbGFzcz0ieyAnaGFzLWJhY2tncm91bmQtZGFuZ2VyJzogdGVzdC5GYWlsaW5nLCAnaGFzLWJhY2tncm91bmQtc3VjY2Vzcyc6ICF0ZXN0LkZhaWxpbmcgfSI+CgkJCQkJPGgxIGNsYXNzPSJ0aXRsZSBpcy00IGhhcy10ZXh0LXdoaXRlIj4KCQkJCQkJe3sgdGVzdC5OYW1lIH19CgkJCQkJPC9oMT4KCQkJCQk8ZGl2IGNsYXNzPSJjb2x1bW5zIiBzdHlsZT0iaGVpZ2h0OjEwMHB4OyI+CgkJCQkJCTxkaXYgY2xhc3M9ImNvbHVtbiBpcy1vbmUtdGhpcmQiPgoJCQkJCQkJPHAgY2xhc3M9ImlzLXNpemUtNyI+ZmFpbGluZzoge3sgdGVzdC5GYWlsaW5nIH19PC9wPgoJCQkJCQkJPHAgY2xhc3M9ImlzLXNpemUtNyI+cGFzcyByYXRlOiB7eyBNYXRoLnJvdW5kKCgodGVzdC5TdWNjZXNzZXMvKHRlc3QuU3VjY2Vzc2VzK3Rlc3QuRmFpbHVyZXMpKSAqIDEwMCl8fDApIH19JTwvcD4KCQkJCQkJPC9kaXY+CgkJCQkJCTxkaXYgc3R5bGU9IgoJCQkJCQlvdmVyZmxvdy15OiBzY3JvbGw7IAoJCQkJCQlvdmVyZmxvdy14OiBzY3JvbGw7IAoJCQkJCQlwYWRkaW5nOiAwLjVyZW07IAoJCQkJCQltYXJnaW4tcmlnaHQ6IDEuNXJlbTsKCQkJCQkJYm9yZGVyLXJhZGl1czogM3B4OwoJCQkJCQkiIGNsYXNzPSJoYXMtYmFja2dyb3VuZC1ncmV5LWRhcmsgY29sdW1uIGlzLXR3by10aGlyZHMiIHYtaWY9InRlc3QuRmFpbGluZyI+CgkJCQkJCQk8cCBzdHlsZT0id2hpdGUtc3BhY2U6IHByZTsiIGNsYXNzPSJpcy1zaXplLTciIHYtaWY9InRlc3QuRmFpbGluZyI+e3t0ZXN0Lkxhc3RGYWlsdXJlT3V0cHV0fX08L3A+CgkJCQkJCTwvZGl2PgoJCQkJCTwvZGl2PgoJCQkJPC9kaXY+CgkJCTwvZGl2PgoJCTwvZGl2PgoJPC9kaXY+CjwvZGl2Pgo=\"")
	}
